---
title: "Factors Associated With Febrile illnesses in Children  in 27 Countries of Sub-Saharan Africa"
author: "Paddy Ssentongo, MD, PhD"
output: html_notebook
---



```{r}
# LOAD REQUIRED PACKAGES AND FUNCTIONS -----------------------------------------
if (!require("pacman")) install.packages("pacman")
pkgs = c("spatstat", "sf", "dplyr", "sparr", "mgcv", "mgcViz", "rgeoboundaries","readxl","reshape", "raster", "tmap","surveillance", "sp", "hhh4addon","stringr", "plotly","RColorBrewer", "ggplot2") # package names
pacman::p_load(pkgs, character.only = T)

```



```{r}
rm(list=ls())

dat=read.csv("data/Estimates.csv", header = T)


```


```{r}
ggplot(dat) +
  geom_vline(xintercept = 1, linetype = 2, col = "blue", size = .6) +
  #geom_pointrange(aes(x = RR, y = reorder(Variable, desc(RR)), xmin = UCI, xmax = LCI), size = .2) +
  geom_pointrange(aes(x = RR, y = reorder(Variable, (RR)), xmin = UCI, xmax = LCI), size = .4) +
  labs(x = "Odds Ratio (95%CI)", y = "Variables") +
  theme_bw() +
  theme(
    axis.title.x=element_text(angle=0, color='black',face = "bold",size = 14),
    axis.title.y=element_text(angle=90, color='black', face='bold', size=14),
     axis.text.y=element_text(angle=0, color='black', face='plain', size=14),
     axis.text.x=element_text(angle=0, color='black',face = "plain",size = 14)
  )

ggsave("figs/Estimates.pdf", width = 7, height = 8)  

# Age 1: 0-6 months (neonates and early infant)=Reference
# Age 2: 7-24 months (Age 1)
# > 25 -59  months * Age 2)

# Maternal

# 15-29( )
# 30- 39
# 40 and above (reference)

```





```{r}
# LOAD REQUIRED PACKAGES AND FUNCTIONS -----------------------------------------
if (!require("pacman")) install.packages("pacman")
pkgs = c("sf", "tmap", "dplyr", "ggplot2") # package names
pacman::p_load(pkgs, character.only = T)

# LOAD DATA --------------------------------------------------------------------
#world <- st_read("africa.gpkg")
world <- st_read("africa_plot.gpkg")

df <- readr::read_csv(file = "Africa.csv")
#hdi<- readr::read_csv(file = "HDI.csv")

# DATA PREPARATION -------------------------------------------------------------
pworld <- world %>%
  left_join(df[c("Country", "Prevalence", "ID")], 
            by = c("name" = "Country")) 
  
quantile(c(pworld$Prevalence), na.rm = T,
         probs = seq(0, 1, l = 50)) %>% 
  round()

tm_shape(pworld) +
  tm_polygons(col = c("Prevalence"),
              title = "Prevalence (%) ", 
              palette = "-RdYlBu", border.col = "black",
              style = "cont", breaks = c(10, 20, 30, 40),
               #style = c("cont", "pretty"),
              lwd = .5, textNA = "No data", colorNA = "grey90") +
  tm_compass(position = c("LEFT", "bottom"), size = 1) +
    tm_scale_bar(position = c(0.06, "BOTTOM"), width = 0.1, text.size = .6) +
  tm_layout(asp = 0, outer.margins = 0, legend.title.size = 1,
            legend.text.size = 0.65, legend.outside.size = 0.15,
            legend.outside = T, design.mode = F,
            panel.labels = c("Prevalence of fever in under 5 years"))

tmap_save(filename = "figs/panels.png", width = 8, height = 3 * 3)
tmap_save(filename = "figs/panels.pdf", width = 8, height = 3 * 3)
```


```{r}

dat=read.csv("data/heatmap3.csv")


l <- reshape(dat, 
  varying = c("Poorest.HH.wealth","Not.Working","Not.Married","Rural","No.Vitamin.A.Supplememt","Respiratory.infection", "Not.fully.vaccinated","Unsafe.stool.disposal", "ANC.visits", "Age.1", "Age.2", "Lack.of.education", "Lack.of.family.planning", "Male","Indoor.Pollution", "Diarrhea", "Unsafe.water", "Young.Mother", "Breastfeeding"), 
  v.names = "value",
  timevar = "variable", 
  times = c("Poorest\nHH\nwealth","Mother\nnot\nworking","Mother\nnot\nMarried","Rural\nresidence","No\nVitamin A\nSupplement", "Respiratory\ninfection", "Not\nfully\nvaccinated","Unsafe\nstool\ndisposal", "< ANC visits", "7 - 22 mo", "25 to 59 mo", "Mother\nnot\neducated", "Inadequate\nfamily\nplanning", "Male","Indoor\npollution", "Diarrhea", "Unsafe\nwater", "Mother\nyoung", "Breastfeeding"),
  new.row.names = 1:10000,
  direction = "long")


OR= cut(l$value,  include.lowest = T, breaks = c(0.3, 0.999,1.1,1.3,2,4.1,24),labels = c("< 1.0", "1.0-1.1", "1.1-1.3","1.3-2.0","2.0-4.0", "> 4.0"))

colors <- colorRampPalette(c("blue", "yellow", "red"))(length(levels(OR)))
ggplot(l, aes(y = reorder(Country, desc(Country)), x=variable, fill=OR)) + 
   labs(x = "Variables", y = "Country") +
   theme(legend.position = "top")+
  geom_tile() +
  geom_text(aes(label = round(value, 1)), color = "gray26", size = 4)+
  scale_fill_manual(values=setNames(colors, levels(OR)))

ggsave("figs/Heatmap7.pdf", width = 15, height = 8)  

```


# B19= Age in months
```{r}
library(haven)
dat1=read_sas("data/child_age_months.sas7bdat")

df <- dat1[ which(dat1$H22=='1'), ]# retain 1


df2 <- df %>%
  #filter(color %in% c("J", "D")) %>%
  group_by(B19, H22) %>%
  summarise(counts = n()) 
head(df2, 4)



# Use position = position_dodge() 
p <- ggplot(df2, aes(x = B19, y = counts)) +
  geom_bar(
    aes(color = B19, fill = B19),
    stat = "identity", position = position_dodge(0.8),
    width = 0.7
    ) 
p

#p + coord_flip()
summary(dat1$B19)
sd(dat1$B19)

```




```{r}
df=read_sas("data/child_age_months.sas7bdat")

df$y= cut(df$B19,  include.lowest = T, breaks = c(0,6,12,18, 24,30, 36, 42, 48,54,60),labels = c("6", "12", "18", "24","30","36","42", "48", "54","60"))

df.plot <- df %>% 
  group_by(y) %>% 
  summarize(fever = sum(H22)/n(),
            nofever = 1-fever)
df.plot$fever=df.plot$fever*100
# Check
rowSums(df.plot[,-1])

# Now plot
df.plot %>% 
  #melt() %>% 
  ggplot(aes(x = y, y = fever, fill = y)) + 
  geom_bar(stat = "identity", position = "stack") + 
  xlab("Age (per 6 months)") + 
  ylab("Proportion with fever (%)") +
  scale_fill_discrete(guide = guide_legend(title = "Age group"))

ggsave("figs/Age1.pdf", width = 15, height = 8)  

```








